services:
  - type: web
    name: org-and-aura
    runtime: node
    plan: free
    region: oregon # Choose oregon, frankfurt, or singapore
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_DEFAULT_EMAIL
        value: admin@organdaura.com
      - key: ADMIN_DEFAULT_PASSWORD
        sync: false
